-- MySQL Script generated by MySQL Workbench
-- Sat Feb 26 16:32:55 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mvc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mvc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mvc` DEFAULT CHARACTER SET utf8 ;
USE `mvc` ;

-- -----------------------------------------------------
-- Table `mvc`.`dates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvc`.`dates` (
  `id_date` INT(11) NOT NULL,
  `date` DATE NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_date`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mvc`.`schedules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvc`.`schedules` (
  `id_schedule` INT(11) NOT NULL,
  `schedule` TIME NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_schedule`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mvc`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvc`.`roles` (
  `id_rol` INT(11) NOT NULL,
  `rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mvc`.`contactos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvc`.`contactos` (
  `id_contacto` INT(11) NOT NULL,
  `num_telefono` VARCHAR(45) NULL DEFAULT NULL,
  `num_celular` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_contacto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mvc`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvc`.`users` (
  `id_users` INT(11) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `p_nombre` VARCHAR(45) NOT NULL,
  `s_nombre` VARCHAR(45) NULL DEFAULT NULL,
  `p_apellido` VARCHAR(45) NOT NULL,
  `s_apellido` VARCHAR(45) NULL DEFAULT NULL,
  `roles_id_rol` INT(11) NOT NULL,
  `contactos_id_contacto` INT(11) NOT NULL,
  PRIMARY KEY (`id_users`),
  INDEX `fk_users_roles_idx` (`roles_id_rol` ASC) VISIBLE,
  INDEX `fk_users_contactos1_idx` (`contactos_id_contacto` ASC) VISIBLE,
  CONSTRAINT `fk_users_contactos1`
    FOREIGN KEY (`contactos_id_contacto`)
    REFERENCES `mvc`.`contactos` (`id_contacto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_users_roles`
    FOREIGN KEY (`roles_id_rol`)
    REFERENCES `mvc`.`roles` (`id_rol`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mvc`.`details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvc`.`details` (
  `id_detail` INT(11) NOT NULL,
  `detail` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`id_detail`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mvc`.`reservations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvc`.`reservations` (
  `id_reservation` INT(11) NOT NULL,
  `amount_people` INT(3) NOT NULL,
  `status` VARCHAR(20) NULL DEFAULT NULL,
  `dates_id_date` INT(11) NOT NULL,
  `schedules_id_schedule` INT(11) NOT NULL,
  `users_id_users` INT(11) NOT NULL,
  `details_id_detail` INT(11) NOT NULL,
  `services_id_service` INT(11) NOT NULL,
  PRIMARY KEY (`id_reservation`),
  INDEX `fk_reservations_dates1_idx` (`dates_id_date` ASC) VISIBLE,
  INDEX `fk_reservations_schedules1_idx` (`schedules_id_schedule` ASC) VISIBLE,
  INDEX `fk_reservations_users1_idx` (`users_id_users` ASC) VISIBLE,
  INDEX `fk_reservations_details1_idx` (`details_id_detail` ASC) VISIBLE,
  INDEX `fk_reservations_services1_idx` (`services_id_service` ASC) VISIBLE,
  CONSTRAINT `fk_reservations_dates1`
    FOREIGN KEY (`dates_id_date`)
    REFERENCES `mvc`.`dates` (`id_date`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reservations_details1`
    FOREIGN KEY (`details_id_detail`)
    REFERENCES `mvc`.`details` (`id_detail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservations_schedules1`
    FOREIGN KEY (`schedules_id_schedule`)
    REFERENCES `mvc`.`schedules` (`id_schedule`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reservations_services1`
    FOREIGN KEY (`services_id_service`)
    REFERENCES `mvc`.`services` (`id_service`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reservations_users1`
    FOREIGN KEY (`users_id_users`)
    REFERENCES `mvc`.`users` (`id_users`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mvc`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvc`.`services` (
  `id_service` INT(11) NOT NULL,
  `service` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_service`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mvc`.`reservations_has_services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvc`.`reservations_has_services` (
  `reservations_id_reservation` INT NOT NULL,
  `services_id_services` INT NOT NULL,
  PRIMARY KEY (`reservations_id_reservation`, `services_id_services`),
  INDEX `fk_reservations_has_services_services1_idx` (`services_id_services` ASC) VISIBLE,
  INDEX `fk_reservations_has_services_reservations1_idx` (`reservations_id_reservation` ASC) VISIBLE,
  CONSTRAINT `fk_reservations_has_services_reservations1`
    FOREIGN KEY (`reservations_id_reservation`)
    REFERENCES `mvc`.`reservations` (`id_reservation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservations_has_services_services1`
    FOREIGN KEY (`services_id_services`)
    REFERENCES `mvc`.`services` (`id_services`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvc`.`contactos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvc`.`contactos` (
  `id_contacto` INT(11) NOT NULL,
  `num_telefono` VARCHAR(45) NULL DEFAULT NULL,
  `num_celular` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_contacto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mvc`.`dates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvc`.`dates` (
  `id_date` INT(11) NOT NULL,
  `date` DATE NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_date`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mvc`.`details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvc`.`details` (
  `id_detail` INT(11) NOT NULL,
  `detail` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`id_detail`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mvc`.`menus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvc`.`menus` (
  `id_menu` INT(11) NOT NULL,
  `title_menu` VARCHAR(70) NOT NULL,
  `description_menu` VARCHAR(250) NOT NULL,
  `price_menu` INT(45) NULL DEFAULT NULL,
  `img_menu` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`id_menu`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mvc`.`menus_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvc`.`menus_categories` (
  `id_category` INT(11) NOT NULL,
  `category` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_category`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mvc`.`menus_has_menus_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvc`.`menus_has_menus_categories` (
  `menus_id_menu` INT(11) NOT NULL,
  `menus_categories_id_category` INT(11) NOT NULL,
  PRIMARY KEY (`menus_id_menu`, `menus_categories_id_category`),
  INDEX `fk_menus_has_menus_categories_menus_categories1_idx` (`menus_categories_id_category` ASC) VISIBLE,
  INDEX `fk_menus_has_menus_categories_menus1_idx` (`menus_id_menu` ASC) VISIBLE,
  CONSTRAINT `fk_menus_has_menus_categories_menus1`
    FOREIGN KEY (`menus_id_menu`)
    REFERENCES `mvc`.`menus` (`id_menu`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_menus_has_menus_categories_menus_categories1`
    FOREIGN KEY (`menus_categories_id_category`)
    REFERENCES `mvc`.`menus_categories` (`id_category`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mvc`.`menu_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvc`.`menu_categories` (
  `id_menu_categories` INT(11) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_menu_categories`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mvc`.`menus_has_menu_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvc`.`menus_has_menu_categories` (
  `menus_id_menu` INT(11) NOT NULL,
  `menu_categories_id_menu_categories` INT(11) NOT NULL,
  PRIMARY KEY (`menus_id_menu`, `menu_categories_id_menu_categories`),
  INDEX `fk_menus_has_menu_categories_menu_categories1_idx` (`menu_categories_id_menu_categories` ASC) VISIBLE,
  INDEX `fk_menus_has_menu_categories_menus1_idx` (`menus_id_menu` ASC) VISIBLE,
  CONSTRAINT `fk_menus_has_menu_categories_menu_categories1`
    FOREIGN KEY (`menu_categories_id_menu_categories`)
    REFERENCES `mvc`.`menu_categories` (`id_menu_categories`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_menus_has_menu_categories_menus1`
    FOREIGN KEY (`menus_id_menu`)
    REFERENCES `mvc`.`menus` (`id_menu`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mvc`.`schedules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvc`.`schedules` (
  `id_schedule` INT(11) NOT NULL,
  `schedule` TIME NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_schedule`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mvc`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvc`.`services` (
  `id_service` INT(11) NOT NULL,
  `service` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_service`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mvc`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvc`.`roles` (
  `id_rol` INT(11) NOT NULL,
  `rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mvc`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvc`.`users` (
  `id_users` INT(11) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `p_nombre` VARCHAR(45) NOT NULL,
  `s_nombre` VARCHAR(45) NULL DEFAULT NULL,
  `p_apellido` VARCHAR(45) NOT NULL,
  `s_apellido` VARCHAR(45) NULL DEFAULT NULL,
  `roles_id_rol` INT(11) NOT NULL,
  `contactos_id_contacto` INT(11) NOT NULL,
  PRIMARY KEY (`id_users`),
  INDEX `fk_users_roles_idx` (`roles_id_rol` ASC) VISIBLE,
  INDEX `fk_users_contactos1_idx` (`contactos_id_contacto` ASC) VISIBLE,
  CONSTRAINT `fk_users_contactos1`
    FOREIGN KEY (`contactos_id_contacto`)
    REFERENCES `mvc`.`contactos` (`id_contacto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_users_roles`
    FOREIGN KEY (`roles_id_rol`)
    REFERENCES `mvc`.`roles` (`id_rol`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mvc`.`reservations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvc`.`reservations` (
  `id_reservation` INT(11) NOT NULL,
  `amount_people` INT(3) NOT NULL,
  `status` VARCHAR(20) NULL DEFAULT NULL,
  `dates_id_date` INT(11) NOT NULL,
  `schedules_id_schedule` INT(11) NOT NULL,
  `users_id_users` INT(11) NOT NULL,
  `details_id_detail` INT(11) NOT NULL,
  `services_id_service` INT(11) NOT NULL,
  PRIMARY KEY (`id_reservation`),
  INDEX `fk_reservations_dates1_idx` (`dates_id_date` ASC) VISIBLE,
  INDEX `fk_reservations_schedules1_idx` (`schedules_id_schedule` ASC) VISIBLE,
  INDEX `fk_reservations_users1_idx` (`users_id_users` ASC) VISIBLE,
  INDEX `fk_reservations_details1_idx` (`details_id_detail` ASC) VISIBLE,
  INDEX `fk_reservations_services1_idx` (`services_id_service` ASC) VISIBLE,
  CONSTRAINT `fk_reservations_dates1`
    FOREIGN KEY (`dates_id_date`)
    REFERENCES `mvc`.`dates` (`id_date`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reservations_details1`
    FOREIGN KEY (`details_id_detail`)
    REFERENCES `mvc`.`details` (`id_detail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservations_schedules1`
    FOREIGN KEY (`schedules_id_schedule`)
    REFERENCES `mvc`.`schedules` (`id_schedule`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reservations_services1`
    FOREIGN KEY (`services_id_service`)
    REFERENCES `mvc`.`services` (`id_service`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reservations_users1`
    FOREIGN KEY (`users_id_users`)
    REFERENCES `mvc`.`users` (`id_users`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mvc`.`reservations_has_menus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvc`.`reservations_has_menus` (
  `reservations_id_reservation` INT(11) NOT NULL,
  `menus_id_menu` INT(11) NOT NULL,
  `user_id` INT(25) NULL DEFAULT NULL,
  PRIMARY KEY (`reservations_id_reservation`, `menus_id_menu`),
  INDEX `fk_reservations_has_menus_menus1_idx` (`menus_id_menu` ASC) VISIBLE,
  INDEX `fk_reservations_has_menus_reservations1_idx` (`reservations_id_reservation` ASC) VISIBLE,
  CONSTRAINT `fk_reservations_has_menus_menus1`
    FOREIGN KEY (`menus_id_menu`)
    REFERENCES `mvc`.`menus` (`id_menu`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reservations_has_menus_reservations1`
    FOREIGN KEY (`reservations_id_reservation`)
    REFERENCES `mvc`.`reservations` (`id_reservation`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
